DROP TABLE FOURNIR;
DROP TABLE TRAVAILLER;
DROP TABLE FOURNISSEUR ;
DROP TABLE MATCHS;
DROP TABLE BUVETTE ;
DROP TABLE STADE;
DROP TABLE PRODUIT ;
DROP TABLE EMPLOYE ;



CREATE TABLE EMPLOYE 
(NOE NUMBER(3),
 Nom VARCHAR2(20),
 Prenom VARCHAR2(20),
 DateNaissance DATE,
 CONSTRAINT pk_nume PRIMARY KEY(NOE)
);


CREATE TABLE PRODUIT
(NOP NUMBER(3),
 DESCRIPTIONP VARCHAR2(40),
 TYPEP VARCHAR2(40),
 CATEGORIE VARCHAR2(40),
 CONSTRAINT pk_nOp PRIMARY KEY(NOP)
);

CREATE TABLE STADE
(NOS   NUMBER(3),
 NOMS   VARCHAR2(40),
 VILLES  VARCHAR2(20),
 CONSTRAINT pk_nOs PRIMARY KEY(NOS)
);


CREATE TABLE BUVETTE
(NOB NUMBER(3),
 EMPLACEMENT VARCHAR2(20),
 NOS NUMBER(3),
 CONSTRAINT pk_NOb PRIMARY KEY(NOB),
 CONSTRAINT fk_nos_b FOREIGN KEY(NOS) REFERENCES Stade(NOS)
);



CREATE TABLE MATCHS
(NUMM NUMBER(3),
 Equipe1 VARCHAR2(20),
 Equipe2 VARCHAR2(20),
 DateM DATE,
 HeureM VARCHAR2(10),
 NOS NUMBER(3),
 CONSTRAINT pk_numm PRIMARY KEY(NUMM),
 CONSTRAINT fk_nos_M FOREIGN KEY(NOS)REFERENCES STADE(NOS) 
);


CREATE TABLE FOURNISSEUR
(NOF   NUMBER(3),
 NomF   VARCHAR2(20),
 LigneAdresse VARCHAR2(40),
 CodePostal NUMBER(5),
 VilleF VARCHAR2(40),
 CONSTRAINT pk_nof PRIMARY KEY(NOF)
);


CREATE TABLE TRAVAILLER
(NOE NUMBER(3),
 NUMM NUMBER(3),
 NOB NUMBER(3),  
 HEUREDEBUT VARCHAR2(10),
 HEUREFIN VARCHAR2(10),
 CONSTRAINT pk_prim1 PRIMARY KEY(NOE,NUMM,NOB),
 CONSTRAINT fk_noe_t FOREIGN KEY(NOE)REFERENCES EMPLOYE(NOE) ,
 CONSTRAINT fk_nomM_t FOREIGN KEY(NUMM) REFERENCES MATCHS(NUMM), 
 CONSTRAINT fk_noB_t FOREIGN KEY(NOB) REFERENCES BUVETTE(NOB) 
);

CREATE TABLE FOURNIR
(DATEL DATE,
 NOF NUMBER(3),
 NOP NUMBER(3),
 NOS NUMBER(3),
 QUANTITE NUMBER(4),
 PRIXUNITAIRE VARCHAR2(40),
 CONSTRAINT pk_fournir PRIMARY KEY(DATEL,NOF,NOP,NOS),
 CONSTRAINT fk_f1 FOREIGN KEY(NOF)REFERENCES FOURNISSEUR(NOF) ,
 CONSTRAINT fk_p1 FOREIGN KEY(NOP)REFERENCES PRODUIT(NOP), 
 CONSTRAINT fk_s1 FOREIGN KEY(NOS)REFERENCES STADE(NOS) 
);

INSERT INTO EMPLOYE(NOE, NOM, PRENOM, DATENAISSANCE)
VALUES(1, 'Fleur', 'Deschamps', DATE'1995-03-04' );

INSERT INTO PRODUIT(NOP,DESCRIPTIONP, TYPEP,CATEGORIE)
VALUES(1,'Sandwichs chevre tomate', 'vegetarien', 'sale');

INSERT INTO PRODUIT(NOP,DESCRIPTIONP, TYPEP,CATEGORIE)
VALUES(2,'Donuts chocolat', 'vegetarien', 'sucre');

INSERT INTO PRODUIT(NOP,DESCRIPTIONP, TYPEP,CATEGORIE)
VALUES(3,'Sandwichs thon mayo',	'viande','sale');

INSERT INTO STADE(NOS, NOMS,VILLES)
VALUES(1, 'STADE 1', 'TOULOUSE');

INSERT INTO BUVETTE(NOB, EMPLACEMENT,NOS)
VALUES(1, 'Aile Ouest', 1);

INSERT INTO BUVETTE(NOB, EMPLACEMENT, NOS)
VALUES(2, 'Aile Est', 1);

INSERT INTO MATCHS(NUMM, EQUIPE1,EQUIPE2,DATEM,HEUREM,NOS)
VALUES(1,'Equipe A','Equipe B',DATE'2019-06-11','20:00',1);

INSERT INTO MATCHS(NUMM, EQUIPE1,EQUIPE2,DATEM,HEUREM,NOS)
VALUES(2,'Equipe A','Equipe B',DATE'2019-06-11','19:00',1);

INSERT INTO FOURNISSEUR(NOF,NOMF,LIGNEADRESSE,CODEPOSTAL,VILLEF)
VALUES(1,'SoGood','21 rue de la R�publique',75000,'Paris');

INSERT INTO FOURNISSEUR(NOF,NOMF,LIGNEADRESSE,CODEPOSTAL,VILLEF)
VALUES(2,'SoBon','11 route de Paris',35000,'Rennes');

INSERT INTO TRAVAILLER(NOE, NUMM, NOB, HEUREDEBUT,HEUREFIN)
VALUES(1, 1, 1, '19:00','20:00');

INSERT INTO TRAVAILLER(NOE, NUMM, NOB, HEUREDEBUT,HEUREFIN)
VALUES(1, 2, 2, '20:30','22:00');

INSERT INTO fournir(DATEL,NOF,NOP,NOS, QUANTITE,PRIXUNITAIRE)
VALUES(DATE'2019-06-11',1,1,1,250,'1,60 � pi�ce');

INSERT INTO fournir(DATEL,NOF,NOP,NOS, QUANTITE,PRIXUNITAIRE)
VALUES(DATE'2019-06-11',1,2,1,130,'1,25 � pi�ce');

INSERT INTO fournir(DATEL,NOF,NOP,NOS, QUANTITE,PRIXUNITAIRE)
VALUES(DATE'2019-06-11',2,3,1,130,'1,35	� pi�ce');


DELETE FROM fournir;
DELETE FROM TRAVAILLER;
DELETE FROM FOURNISSEUR;
DELETE FROM MATCHS;
DELETE FROM BUVETTE;
DELETE FROM STADE;
DELETE FROM PRODUIT;
DELETE FROM EMPLOYE;


INSERT INTO EMPLOYE(NOE, NOM, PRENOM, DATENAISSANCE)
SELECT distinct gilles_hubert.tp4_buvettes.nume, NOM, PRENOM, datenaissance  
    FROM gilles_hubert.tp4_buvettes  where gilles_hubert.tp4_buvettes.nume is not null;

INSERT INTO PRODUIT(NOP,DESCRIPTIONP, TYPEP,CATEGORIE)
SELECT distinct  NUMP, description, type, categorie  
    FROM gilles_hubert.tp4_buvettes where gilles_hubert.tp4_buvettes.nump is not null;

INSERT INTO STADE(NOS, NOMS,VILLES)
SELECT distinct  NUMs, NOMS, VILLE
    FROM gilles_hubert.tp4_buvettes where gilles_hubert.tp4_buvettes.numS is not null;
    
INSERT INTO BUVETTE(NOB, EMPLACEMENT,NOS)
SELECT distinct  NUMB, EMPLACEMENT, NUMS
    FROM gilles_hubert.tp4_buvettes where gilles_hubert.tp4_buvettes.numB is not null ;
    
INSERT INTO MATCHS(NUMM, EQUIPE1,EQUIPE2,DATEM,HEUREM,NOS)
SELECT distinct  NUMM, EQUIPE1, EQUIPE2, DATEM, HEUREM,NUMS
    FROM gilles_hubert.tp4_buvettes where gilles_hubert.tp4_buvettes.numM is not null ;


INSERT INTO FOURNISSEUR(NOF,NOMF,LIGNEADRESSE,CODEPOSTAL,VILLEF)
SELECT distinct  NUMF, NOMF, LIGNEADRESSE, CODEPOSTAL,VILLEF
    FROM gilles_hubert.tp4_buvettes where gilles_hubert.tp4_buvettes.numF is not null ;
    
INSERT INTO TRAVAILLER(NOE, NUMM, NOB, HEUREDEBUT,HEUREFIN)
SELECT distinct  NUME, NUMM, NUMB, HEUREDEBUT,HEUREFIN
    FROM gilles_hubert.tp4_buvettes where gilles_hubert.tp4_buvettes.numM is not null ;
    

INSERT INTO fournir(DATEL,NOF,NOP,NOS, QUANTITE,PRIXUNITAIRE)
SELECT distinct DATEL, NUMF, NUMP,NUMS , QUANTITE, PRIXUNITAIRE
    FROM gilles_hubert.tp4_buvettes where gilles_hubert.tp4_buvettes.DATEL is not null ;