SELECT * FROM PILOTE;
    
SELECT nomPilote, nuPilote FROM PILOTE;
    
SELECT nuCi FROM COURSE;
    
SELECT DISTINCT nuCi FROM COURSE;
    
SELECT ANNEECO, METEO FROM COURSE WHERE NUCI = 2 ; 

SELECT CLASSEMENT, NUPILOTE  FROM EFFECTUER WHERE 
nuCo = 3 UNION SELECT CLASSEMENT, NUPILOTE FROM EFFECTUERQUALIFICATION 
WHERE NUCO = 3;
    
SELECT NUCO, ANNEECO, METEO FROM COURSE WHERE NUCI = 2
ORDER BY ANNEECO ;
   
SELECT  NUCI,NOMCI,PAYSCI,LONGUEURCI FROM CIRCUIT 
ORDER BY PAYSCI DESC;
    
SELECT  NUPILOTE, NOMPILOTE FROM PILOTE WHERE NOMPILOTE LIKE 'F%';
    
SELECT  NUPILOTE FROM APPARTENIR WHERE ANNEE = 2009 
AND NUECURIE in (1,2); 
    
SELECT  NUPILOTE FROM EFFECTUER WHERE NUCO = 9 AND CLASSEMENT <=3;
    
SELECT NUCI, NOMCI, NBTOURS * LONGUEURCI as DistanceTotal 
FROM CIRCUIT ;
    
SELECT COUNT(*) FROM CIRCUIT;
    
SELECT AVG(TEMPS) FROM EFFECTUER WHERE NUCO =1;
    
SELECT NUCO ,AVG(TEMPS) FROM EFFECTUER GROUP BY NUCO ;
    
SELECT  res.NUCO FROM (SELECT NUCO ,AVG(TEMPS) as timeM 
FROM EFFECTUER GROUP BY NUCO) res WHERE res.timeM <=5000 ;
        
SELECT NUPILOTE,COUNT(DISTINCT NUECURIE) from APPARTENIR 
group by NUPILOTE HAVING COUNT(DISTINCT NUECURIE)>=2;
    
SELECT DISTINCT NUPILOTE FROM APPARTENIR a1 
WHERE NUPILOTE in (SELECT NUPILOTE FROM APPARTENIR a2 
WHERE a1.NUECURIE <> a2.NUECURIE  )  ;
    
SELECT nuCO , anneeCo, nomCi , paysCi from COURSE, CIRCUIT;
--produit cartesienne
SELECT nuCO , anneeCo, nomCi , paysCi from COURSE, CIRCUIT
WHERE CIRCUIT.NUCI = COURSE.NUCI;
--jointure
SELECT DISTINCT nomCi , paysCi from circuit , course
WHERE circuit.NUCI = course.NUCI
AND course.METEO = 'pluie';
    
SELECT DISTINCT nomPilote, prenomPilote, nationalite from pilote , APPARTENIR , ECURIE 
WHERE pilote.NUPILOTE = APPARTENIR.NUPILOTE 
AND ECURIE.NUECURIE = APPARTENIR.NUECURIE 
AND ECURIE.NOMECURIE = 'Ferrari' ; 
    
SELECT DISTINCT nomPilote, prenomPilote, nationalite from pilote , APPARTENIR , ECURIE 
WHERE pilote.NUPILOTE = APPARTENIR.NUPILOTE 
AND ECURIE.NUECURIE = APPARTENIR.NUECURIE 
AND ECURIE.NOMECURIE = 'Ferrari' 
AND APPARTENIR.ANNEE = 2006;     
  
SELECT DISTINCT NOMPILOTE, PRENOMPILOTE, NATIONALITE, TEMPSTOUR FROM PILOTE, CIRCUIT, EFFECTUER, COURSE
WHERE PILOTE.NUPILOTE=EFFECTUER.NUPILOTE 
AND EFFECTUER.NUCO=COURSE.NUCO 
AND COURSE.NUCI=CIRCUIT.NUCI 
AND NOMCI='Silverstone' and CLASSEMENT=1;

SELECT NUCI from CIRCUIT MINUS SELECT NUCI from COURSE;

SELECT DISTINCT NOMPILOTE, PRENOMPILOTE  FROM PILOTE, CIRCUIT, EFFECTUER, COURSE
WHERE PILOTE.NUPILOTE=EFFECTUER.NUPILOTE 
AND EFFECTUER.NUCO=COURSE.NUCO 
AND COURSE.NUCI=CIRCUIT.NUCI 
AND NOMCI='Silverstone' 
AND CLASSEMENT=1 
INTERSECT SELECT DISTINCT NOMPILOTE, PRENOMPILOTE  FROM PILOTE, CIRCUIT, EFFECTUER, COURSE 
WHERE PILOTE.NUPILOTE=EFFECTUER.NUPILOTE 
AND EFFECTUER.NUCO=COURSE.NUCO 
AND COURSE.NUCI=CIRCUIT.NUCI 
AND NOMCI='Gilles-Villeneuve' 
AND CLASSEMENT=1;

SELECT DISTINCT NOMCI FROM CIRCUIT 
MINUS SELECT DISTINCT NOMCI FROM CIRCUIT,COURSE
WHERE COURSE.NUCI = CIRCUIT.NUCI and COURSE.ANNEECO=2009 ;

SELECT DISTINCT NOMCI FROM CIRCUIT,COURSE
WHERE COURSE.NUCI = CIRCUIT.NUCI
MINUS SELECT DISTINCT NOMCI FROM CIRCUIT,COURSE 
WHERE COURSE.NUCI = CIRCUIT.NUCI 
AND COURSE.ANNEECO=2009;

SELECT DISTINCT NOMCI FROM CIRCUIT,COURSE 
WHERE COURSE.NUCI = CIRCUIT.NUCI 
MINUS SELECT DISTINCT NOMCI FROM CIRCUIT,COURSE 
WHERE COURSE.NUCI = CIRCUIT.NUCI and COURSE.ANNEECO<2009;
    
SELECT DISTINCT PILOTE.NOMPILOTE, EFFECTUER.NUCO FROM PILOTE, EFFECTUER, EFFECTUERQUALIFICATION 
WHERE EFFECTUERQUALIFICATION.NUCO=EFFECTUER.NUCO 
AND EFFECTUERQUALIFICATION.NUPILOTE = PILOTE.NUPILOTE 
AND PILOTE.NUPILOTE = EFFECTUER.NUPILOTE 
AND EFFECTUERQUALIFICATION.CLASSEMENT > EFFECTUER.CLASSEMENT;
    
SELECT DISTINCT PILOTE.NOMPILOTE, EFFECTUER.NUCO FROM PILOTE, EFFECTUER, EFFECTUERQUALIFICATION 
WHERE EFFECTUERQUALIFICATION.NUCO=EFFECTUER.NUCO 
AND EFFECTUERQUALIFICATION.NUPILOTE = PILOTE.NUPILOTE 
AND PILOTE.NUPILOTE = EFFECTUER.NUPILOTE 
AND EFFECTUERQUALIFICATION.CLASSEMENT = EFFECTUER.CLASSEMENT;
    
SELECT DISTINCT PILOTE.NOMPILOTE, EFFECTUERQUALIFICATION.NUCO FROM PILOTE, EFFECTUERQUALIFICATION 
WHERE PILOTE.NUPILOTE = EFFECTUERQUALIFICATION.NUPILOTE  
AND EFFECTUERQUALIFICATION.NUPILOTE not in (select EFFECTUER.NUPILOTE from EFFECTUER where EFFECTUERQUALIFICATION.NUCO = EFFECTUER.NUCO );

SELECT distinct ECURIE.nomecurie, APPARTENIR.annee, COUNT(NUpilote) from APPARTENIR , ECURIE
WHERE APPARTENIR.NUECURIE= ECURIE.NUECURIE 
GROUP BY ECURIE.NOMECURIE, APPARTENIR.ANNEE;
    